name = "Construct"
author = "Falxie_"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "517712ac0440dd17406bdea4c98e5d6505c3961e5415a29447ce6dfa4d3ee523"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
