name = "Construct"
author = "Falxie_"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4159a4440f30f068c0165b6f444772910b29004f3719af3bfbf2f4cbf817166"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
