name = "Construct"
author = "Falxie_"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc3408767a0da3130e6c263a0dac9f22c637e0ce14fed834df01acc62c5f2770"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
