name = "Construct"
author = "Falxie_"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f6aaf433419d50d1042aeb4e330e03d9ed93ca581360f6ef0413273fac2d96"

[versions]
forge = "40.1.76"
minecraft = "1.18.2"
