name = "Construct"
author = "Falxie_"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d816991555857e5028519eccdea0da2b632e708711c967c2db10088cc3e091e"

[versions]
forge = "40.1.76"
minecraft = "1.18.2"
