name = "Construct"
author = "Falxie_"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "526a417bbeb26242308ccc396de4a670ba3a52e9db52cb0f86d37c6d05ac8349"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
