name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a53f441f1a08de9f09f0a13992d1b96be90473a57cae3c07650006f513aa0dc"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
