name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dbf612619c23e580a279b0756c6e642a75545b33b8170b0b2bd1f52e96f3953"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
