name = "Construct"
author = "Falxie_"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1d04b18c6725041b1b7e351fede604322b590b003634dbaaa859349e56bb0b"

[versions]
forge = "40.1.76"
minecraft = "1.18.2"
