name = "Construct"
author = "Falxie_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d26a6dc21470f9c8731080f476c3b59794c3eb1f9060307e44a933d72da5ee6c"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
