name = "Construct"
author = "Falxie_"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be2719fa26ca090cea0c9f010547895d32a022fa6835acf728ed07a00851dd03"

[versions]
forge = "40.1.84"
minecraft = "1.18.2"
