name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08752d9ed365fd8f691f084d1fe44e1998cc50c0e8fe57f0cc1bbd0a520e1e9"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
