name = "Construct"
author = "Falxie_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "005bb98c3c23bda65c3fca23896af9827282d68d96a48c2c8cc392ed88428009"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
