name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e488e5c947d539ccef3d119c8ff9183b2fe220f435842604229ddbab5e52696"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
