name = "Construct"
author = "Falxie_"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2992f3059ee323e33231fcd6a4520b5c538600b627ec7a689bb05e4a5420b6"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
