name = "Construct"
author = "Falxie_"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc951bd2320a8dc5452d83cf175058f0e9b638665dce6c21cf79a6dac3d58d6d"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
