name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "787c15b1c482de910e4355b798b77a6d2c6de3d2595995382fd710f53b04b18f"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
