name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "513389bc7fb1c5cf5bef72eb17ca26c994d104617014e6d4b8a656342c2a1505"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
