name = "Construct"
author = "Falxie_"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1bb3c7a9f85bc0e7df6e0e64fe0d7eb2ca2d72a4b09b9c439ec7206be663144"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
