name = "Construct"
author = "Falxie_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e72a5a63f06f34556d2da2c436924ff479992ada1aed4ad4eef946cbd7e2cfa8"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
