name = "Construct"
author = "Falxie_"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1cd0027ad9a5e919d229e4f14971c78c99c7f425711b3c8397bb40383315f40"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
