name = "Construct"
author = "Falxie_"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "781947d60e5ea8e2f6123cbcbd943cfaea943ceb91ad2b125e64078b39709a92"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
