name = "Construct"
author = "Falxie_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e20d37a5dc3fc4c0d9e14a2ef08964400b35e68b46e50240545d418eae3939af"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
