name = "Construct"
author = "Falxie_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72883c8b9a81c305884da4107ba8a51913f40a49f161d492e180d401a65ffb0f"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
