name = "Construct"
author = "Falxie_"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "335f093bbe17a5a8202ff1884b6d5836cd2ac805a4325126dfa839635271a692"

[versions]
forge = "40.1.74"
minecraft = "1.18.2"
