
["Version Configuration"]
	# Define a version here. On world load the mod will look up the serverconfig version and reset all files that specified up to the newest version.
	# Example: ["1=minecraft","2=forge"] will reset minecraft and forge config on first load, but will only reset forge if the world has been loaded before with only version 1 defined
	versions = ["1=cofh_core", "1=comforts", "1=corpse", "1=create", "1=curios", "1=doubleslabs", "1=ensorcellation", "1=etched", "1=fastleafdecay", "1=forge", "1=jei", "1=mantle", "1=pickupnotifier", "1=skinnedlanterns"]

["File Deleter"]
	# This is intended for deleting files for pack updates. This is a last resort! Replace with empty files instead when possible. The file will be deleted every launch if it exists! Specify the path to the file. Comma Separated List. Example: scripts/badscript.zs
	files = [""]
	# By default Folders are only deleted if they are empty. Set to true to change that.
	deleteFoldersWithContent = false

